# Disable the built-in OpenTelemetry Collector sub-chart and Jager, Prometheus, Graphana since we are using Splunk
opentelemetry-collector:
  enabled: false
jaeger:
  enabled: false
prometheus:
  enabled: false
grafana:
  enabled: false

# Configure default environment variables for all components
# This will add/override these environment variables for every microservice in the demo.
default:
  envOverrides:
    - name: NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP
    - name: OTEL_COLLECTOR_NAME
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP